### ISSUE TITLE
why do these have to get stacked?

### ISSUE THREAD

**Issue by SBFRF** [anderdyl/objectiveMapping#1]
https://github.com/anderdyl/objectiveMapping/blob/3acff88eaaf07c048c80831be33243ec9cc52c0d/objMapPrep.py#L38

hey dylan why do these have to get stacked? if i'm understanding correctly, when the data are not square, (ie y is longer than x) this line fails.

**Comment by anderdyl** [comment]
Hmm, you shouldn't ever pass that different lengths of x and y ... that is all x's and all y's being collapsed to a format needed for the "contains_points" function below in the code. in other words that is making a 2xN array where N is all points in the data. Sounds like you have an x and y vector that are the edge of the matrix, prior to meshgrid?

**Comment by SBFRF** [comment]
fixed!
